const { chromium } = require('playwright')
const { readFileSync, mkdirSync } = require('node:fs')
const { parseEnv } = require('node:util')
const path = require('node:path')
const assert = require('node:assert/strict')

async function main() {
  const root = path.resolve(__dirname, '..')
  const config = parseEnv(readFileSync(path.join(root, 'backend/.env'), 'utf8'))
  const output = path.join(root, '.runtime', 'screenshots')
  mkdirSync(output, { recursive: true })
  const browser = await chromium.launch({ headless: true, channel: 'chrome' })
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 }, deviceScaleFactor: 1 })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  try {
    await page.goto('http://127.0.0.1:5173')
    await page.getByLabel('管理口令', { exact: true }).fill(config.ADMIN_TOKEN)
    await page.getByRole('button', { name: '进入工作区' }).click()
    await page.getByRole('heading', { name: '报价助手', exact: true }).waitFor()
    await page.screenshot({ path: path.join(output, 'chat-home-desktop.png'), animations: 'disabled' })
    await page.setViewportSize({ width: 390, height: 844 })
    await page.screenshot({ path: path.join(output, 'chat-home-mobile.png'), animations: 'disabled' })
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Chat home overflow')
    await page.setViewportSize({ width: 1440, height: 1050 })
    await page.getByRole('button', { name: /价格明细/ }).click()
    await page.getByRole('button', { name: '新增价格', exact: true }).waitFor()
    await page.getByRole('button', { name: '迷你字', exact: true }).first().waitFor()
    await page.screenshot({ path: path.join(output, 'prices-desktop.png'), animations: 'disabled' })
    await page.getByRole('button', { name: '迷你字', exact: true }).first().click()
    await page.getByRole('tab', { name: /^版本历史 \(\d+\)$/ }).click()
    await page.getByText('原表导入，未发布', { exact: true }).waitFor()
    await page.getByRole('button', { name: '关闭', exact: true }).click()
    await page.getByRole('tab', { name: /^版本历史 \(\d+\)$/ }).waitFor({ state: 'hidden' })
    await page.getByLabel('搜索', { exact: true }).fill('完全不存在的产品测试')
    await page.getByLabel('执行搜索', { exact: true }).click()
    await page.getByText('没有符合条件的价格记录').waitFor()
    await page.getByLabel('重置筛选').click()
    await page.getByRole('button', { name: '迷你字', exact: true }).first().waitFor()
    await page.getByRole('button', { name: '新增价格', exact: true }).click()
    await page.getByRole('dialog', { name: '新增价格' }).getByText('已启用', { exact: true }).waitFor()
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await page.getByText('请填写产品名称和分类').waitFor()
    await page.screenshot({ path: path.join(output, 'price-form-desktop.png') })
    await page.getByRole('button', { name: '取消', exact: true }).click()
    await page.getByRole('button', { name: '规则与案例', exact: true }).click()
    await page.getByText('规则原文 · 尚未启用自动计价').waitFor()
    await page.getByRole('button', { name: '新增规则', exact: true }).click()
    await page.getByRole('dialog', { name: '新增规则' }).waitFor()
    await page.getByRole('button', { name: '取消', exact: true }).click()
    await page.getByRole('button', { name: '来源文件', exact: true }).click()
    await page.getByRole('heading', { name: '项目类常规报价表_完整单价导出.xlsx' }).waitFor()
    await page.screenshot({ path: path.join(output, 'sources-desktop.png'), fullPage: true })
    await page.getByRole('button', { name: '修改记录', exact: true }).click()
    await page.getByRole('button', { name: '查看变更' }).first().click()
    await page.getByRole('dialog', { name: '变更详情' }).waitFor()
    await page.locator('.el-dialog__headerbtn:visible').click()
    await page.getByRole('dialog', { name: '变更详情' }).waitFor({ state: 'hidden' })
    await page.getByRole('button', { name: /价格明细/ }).click()
    await page.getByRole('button', { name: 'D2', exact: true }).click()
    await page.getByRole('dialog', { name: '原表记录' }).waitFor()
    await page.getByText('Sheet1 · 第 2 行').waitFor()
    await page.locator('.el-dialog__headerbtn:visible').click()
    await page.getByRole('dialog', { name: '原表记录' }).waitFor({ state: 'hidden' })
    await page.setViewportSize({ width: 390, height: 844 })
    await page.getByRole('columnheader', { name: '材质 / 厚度' }).waitFor({ state: 'hidden' })
    await page.screenshot({ path: path.join(output, 'prices-mobile.png'), animations: 'disabled' })
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth),
      'Mobile page has unexpected horizontal overflow')
    await page.getByRole('button', { name: '打开导航' }).click()
    await page.getByRole('button', { name: '来源文件', exact: true }).click()
    await page.getByRole('heading', { name: '项目类常规报价表_完整单价导出.xlsx' }).waitFor()
    await page.screenshot({ path: path.join(output, 'sources-mobile.png'), fullPage: true, animations: 'disabled' })
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth),
      'Source page has unexpected horizontal overflow')
    assert.deepEqual(errors, [], 'Browser page errors')
    console.log('PASS: login, lists, search, empty state, validation, rules, sources, audit, history, mobile layouts.')
    console.log('Screenshots: .runtime/screenshots')
  } finally {
    await browser.close()
  }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
