const { chromium } = require('playwright')
const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')

async function main() {
  const root = path.resolve(__dirname, '..')
  const output = path.join(root, '.runtime/screenshots')
  fs.mkdirSync(output, { recursive: true })
  const browser = await chromium.launch({ channel: 'chrome', headless: true })
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } })
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  try {
    await page.goto('http://127.0.0.1:5174')
    await page.getByLabel('管理口令', { exact: true }).fill('ui-test-local-only')
    await page.getByRole('button', { name: '进入工作区' }).click()
    await page.getByRole('heading', { name: '报价助手', exact: true }).waitFor()
    await page.screenshot({ path: path.join(output, 'phase2-empty-desktop.png') })
    await page.getByRole('button', { name: '新建项目表单', exact: true }).click()
    await page.getByLabel('任务名称', { exact: true }).fill('门店导视制作')
    await page.getByLabel('客户名称', { exact: true }).fill('演示客户（测试环境）')
    await page.getByLabel('客户补充说明', { exact: true }).fill('铝牌 300 x 120 mm，厚3mm，共2件。')
    const file = path.join(root, '.runtime/phase2-fixture.png')
    await page.getByRole('dialog', { name: '新建客户需求' }).locator('input[type=file]').setInputFiles(file)
    await page.getByRole('button', { name: '保存资料' }).click()
    await page.getByRole('heading', { name: '门店导视制作' }).waitFor()
    await page.getByRole('button', { name: '明细与报价', exact: true }).click()
    assert(await page.getByRole('button', { name: 'Agent 自动报价', exact: true }).isDisabled())
    await page.locator('.customer-file').first().click()
    await page.locator('.customer-preview img').waitFor()
    await page.screenshot({ path: path.join(output, 'phase2-preview.png'), animations: 'disabled' })
    await page.locator('.el-dialog__headerbtn:visible').click()
    await page.getByRole('dialog', { name: 'phase2-fixture.png' }).waitFor({ state: 'hidden' })
    await page.getByRole('button', { name: '添加明细', exact: true }).click()
    await page.getByLabel('产品名称', { exact: true }).fill('铝牌')
    await page.getByLabel('材质', { exact: true }).fill('铝')
    await page.getByLabel('厚度 (mm)', { exact: true }).fill('3')
    await page.getByLabel('单件宽 (mm)', { exact: true }).fill('300')
    await page.getByLabel('单件高 (mm)', { exact: true }).fill('120')
    await page.getByRole('spinbutton').fill('2')
    await page.getByLabel('工艺', { exact: true }).fill('UV打印')
    await page.getByRole('button', { name: '添加费用', exact: true }).click()
    await page.getByLabel('费用名称').fill('UV打印')
    await page.getByLabel('费用金额').fill('10')
    await page.getByLabel('费用依据').fill('2件，每件5元')
    await page.getByLabel('修改原因', { exact: true }).fill('依据客户标注逐项核实')
    await page.getByText('已核实产品、数量、尺寸和工艺，不确定项已澄清', { exact: true }).click()
    await page.getByRole('button', { name: '保存明细', exact: true }).click()
    await page.getByRole('dialog', { name: '需求明细', exact: true }).waitFor({ state: 'hidden' })
    await page.getByRole('button', { name: '匹配价格', exact: true }).click()
    await page.getByRole('button', { name: '选择', exact: true }).waitFor()
    await page.locator('.el-loading-mask:visible').waitFor({ state: 'hidden' })
    await page.screenshot({ path: path.join(output, 'phase2-candidates.png'), animations: 'disabled' })
    await page.getByRole('button', { name: '选择', exact: true }).click()
    await page.locator('.el-message-box input').fill('规格材质已核对，UV费另计')
    await page.getByRole('button', { name: '选择此价格', exact: true }).click()
    await page.getByText('已关联价格', { exact: true }).waitFor()
    await page.getByRole('button', { name: '计算报价', exact: true }).click()
    await page.getByRole('textbox', { name: '报价条款：税费、运费、安装费、有效期' }).fill('含税，不含运输、安装，报价有效期7天。')
    await page.getByRole('button', { name: '计算草稿', exact: true }).click()
    await page.getByText('报价合计', { exact: true }).waitFor()
    await page.locator('.quote-total').getByText('¥ 31.60', { exact: true }).waitFor()
    await page.screenshot({ path: path.join(output, 'phase2-quote-desktop.png'), animations: 'disabled' })
    await page.getByRole('button', { name: '批准报价', exact: true }).click()
    await page.getByRole('textbox', { name: '审核说明', exact: true }).fill('已逐项核对需求与计价依据')
    await page.getByText('已确认价格适用性、税费、运费、安装费及条款', { exact: true }).click()
    await page.getByRole('button', { name: '批准', exact: true }).click()
    await page.getByRole('button', { name: '导出 CSV', exact: true }).waitFor()
    const downloadPromise = page.waitForEvent('download')
    await page.getByRole('button', { name: '导出 CSV', exact: true }).click()
    const download = await downloadPromise
    assert((await fs.promises.readFile(await download.path(), 'utf8')).includes('31.60'))
    await page.setViewportSize({ width: 390, height: 844 })
    await page.screenshot({ path: path.join(output, 'phase2-quote-mobile.png'), fullPage: true, animations: 'disabled' })
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile overflow')
    await page.getByRole('tab', { name: '需求明细 (1)' }).click()
    await page.screenshot({ path: path.join(output, 'phase2-requirements-mobile.png'), fullPage: true, animations: 'disabled' })
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Requirements mobile overflow')
    await page.setViewportSize({ width: 1440, height: 1050 })
    await page.locator('.el-drawer:visible .el-drawer__header button').click()
    await page.getByRole('dialog', { name: '明细与报价', exact: true }).waitFor({ state: 'hidden' })
    await page.getByRole('button', { name: 'DeepSeek 配置', exact: true }).click()
    await page.getByLabel('API Key', { exact: true }).fill('ui-test-key-never-sent')
    await page.getByRole('button', { name: '保存密钥', exact: true }).click()
    await page.getByRole('dialog', { name: 'DeepSeek 配置' }).waitFor({ state: 'hidden' })
    await page.getByRole('button', { name: '新对话', exact: true }).last().click()
    await page.getByRole('textbox', { name: '消息', exact: true }).fill('自动测试牌，铝材厚3mm，300×120mm，制作2件')
    await page.locator('.chat-composer input[type=file]').setInputFiles(file)
    await page.getByText('授权本次对话资料及候选报价发送至 DeepSeek；补充需求将重新识别并更新报价', { exact: true }).click()
    await page.getByRole('button', { name: '发送消息', exact: true }).click()
    await page.locator('.chat-quote-total').getByText('¥ 21.60', { exact: true }).waitFor()
    await page.locator('.chat-run > details > summary').click()
    assert.equal(await page.locator('.chat-tool-step').count(), 6)
    await page.locator('.el-message:visible').last().waitFor({ state: 'hidden' })
    await page.screenshot({ path: path.join(output, 'agent-desktop.png'), animations: 'disabled', fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 })
    await page.screenshot({ path: path.join(output, 'agent-mobile.png'), animations: 'disabled', fullPage: true })
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Agent mobile overflow')
    await page.getByRole('button', { name: '查看与审核报价', exact: true }).click()
    await page.getByRole('button', { name: '批准报价', exact: true }).click()
    await page.getByRole('textbox', { name: '审核说明', exact: true }).fill('测试：已核对自动草稿')
    await page.getByRole('textbox', { name: '正式报价条款', exact: true }).fill('含税，不含运费和安装，有效期7天。')
    await page.getByText('已确认价格适用性、税费、运费、安装费及条款', { exact: true }).click()
    await page.getByRole('button', { name: '批准', exact: true }).click()
    await page.getByRole('button', { name: '导出 CSV', exact: true }).waitFor()
    await page.locator('.el-drawer:visible .el-drawer__header button').click()
    await page.getByRole('dialog', { name: '明细与报价', exact: true }).waitFor({ state: 'hidden' })
    // Continue the same conversation directly, with no extraction modal.
    await page.getByRole('textbox', { name: '消息', exact: true }).fill('数量仍为2件，请重新核对一次。')
    assert(await page.locator('.chat-consent input').isChecked())
    await page.getByRole('button', { name: '发送消息', exact: true }).click()
    await page.getByText('报价草稿 · V2', { exact: false }).waitFor()
    assert.equal(await page.locator('.chat-run').count(), 2)
    await page.getByRole('button', { name: '新对话', exact: true }).last().click()
    await page.getByRole('textbox', { name: '消息', exact: true }).fill('待核价测试：请整理缺少单价的项目')
    await page.getByText('授权本次对话资料及候选报价发送至 DeepSeek；补充需求将重新识别并更新报价', { exact: true }).click()
    await page.getByRole('button', { name: '发送消息', exact: true }).click()
    await page.getByText('待核价清单 · V1', { exact: false }).waitFor()
    await page.getByRole('dialog', { name: '补充报价信息', exact: true }).waitFor()
    await page.getByRole('button', { name: '稍后补充', exact: true }).click()
    await page.getByRole('dialog', { name: '补充报价信息', exact: true }).waitFor({ state: 'hidden' })
    await page.locator('.chat-quote-total').getByText('成品总价待补充', { exact: true }).waitFor()
    assert(!(await page.locator('.chat-quote-total').innerText()).includes('0.00'))
    await page.locator('.chat-quote .component-references summary').click()
    await page.locator('.chat-quote .component-references').getByText('测试建议单价，非成品价', { exact: true }).first().waitFor()
    assert((await page.locator('.chat-quote .component-references').innerText()).includes('150 元/m²'))
    await page.locator('.case-references summary').click()
    assert((await page.locator('.case-references').innerText()).includes('7920.00'))
    assert((await page.locator('.case-references').innerText()).includes('未套用'))
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Component mobile overflow')
    await page.locator('.el-message:visible').last().waitFor({ state: 'hidden' })
    await page.screenshot({ path: path.join(output, 'component-references-mobile.png'), animations: 'disabled' })
    await page.setViewportSize({ width: 1440, height: 1050 })
    await page.screenshot({ path: path.join(output, 'component-references-desktop.png'), animations: 'disabled' })
    await page.setViewportSize({ width: 390, height: 844 })
    await page.getByRole('button', { name: '查看与审核报价', exact: true }).click()
    await page.locator('.quote-total').getByText('成品总价待补充', { exact: true }).waitFor()
    assert.equal(await page.getByRole('button', { name: '批准报价', exact: true }).count(), 0)
    await page.screenshot({ path: path.join(output, 'pending-quote-mobile.png'), animations: 'disabled' })
    await page.locator('.el-drawer:visible .el-drawer__header button').click()
    await page.getByRole('dialog', { name: '明细与报价', exact: true }).waitFor({ state: 'hidden' })
    await page.getByRole('button', { name: '补充后继续', exact: true }).click()
    await page.getByRole('dialog', { name: '补充报价信息', exact: true }).waitFor()
    await page.screenshot({ path: path.join(output, 'quote-review-mobile.png'), animations: 'disabled' })
    await page.getByRole('button', { name: '补充资料或单价', exact: true }).click()
    await page.getByRole('dialog', { name: '需求明细', exact: true }).waitFor()
    await page.getByRole('textbox', { name: '人工不含税单价（元/件）', exact: true }).fill('100')
    await page.getByRole('textbox', { name: '人工补价依据及包含范围', exact: true }).fill('人工核定制作价，不含安装')
    await page.getByLabel('修改原因', { exact: true }).fill('补充缺失单价')
    await page.getByRole('button', { name: '保存明细', exact: true }).click()
    await page.getByRole('dialog', { name: '需求明细', exact: true }).waitFor({ state: 'hidden' })
    await page.getByRole('button', { name: '继续报价', exact: true }).click()
    await page.locator('.chat-quote-total').getByText('¥ 200.00', { exact: true }).waitFor()
    await page.getByText('报价草稿 · V2', { exact: false }).waitFor()
    await page.getByRole('button', { name: '新对话', exact: true }).last().click()
    await page.getByRole('textbox', { name: '消息', exact: true }).fill('纯文字报价：自动测试牌，铝厚3mm，300×120mm，2件')
    await page.getByText('授权本次对话资料及候选报价发送至 DeepSeek；补充需求将重新识别并更新报价', { exact: true }).click()
    await page.getByRole('button', { name: '发送消息', exact: true }).click()
    await page.locator('.chat-quote-total').getByText('¥ 21.60', { exact: true }).waitFor()
    await page.getByRole('button', { name: '会话列表', exact: true }).click()
    await page.locator('.chat-history-item').filter({ hasText: '自动测试牌，铝材厚3mm' }).click()
    await page.getByText('报价草稿 · V2', { exact: false }).waitFor()
    await page.getByRole('button', { name: '新对话', exact: true }).last().click()
    await page.getByRole('textbox', { name: '消息', exact: true }).fill('单价优先测试：数量未知，先报成品单价与材料成本')
    await page.locator('.chat-composer input[type=file]').setInputFiles(file)
    await page.getByText('授权本次对话资料及候选报价发送至 DeepSeek；补充需求将重新识别并更新报价', { exact: true }).click()
    await page.getByRole('button', { name: '发送消息', exact: true }).click()
    await page.getByRole('dialog', { name: '补充报价信息', exact: true }).waitFor()
    await page.getByRole('button', { name: '稍后补充', exact: true }).click()
    await page.getByRole('dialog', { name: '补充报价信息', exact: true }).waitFor({ state: 'hidden' })
    await page.locator('.chat-quote').getByText('成品单价：¥ 10.80 / 件', { exact: true }).waitFor()
    assert(!(await page.locator('.chat-quote-total').innerText()).includes('10.80'))
    await page.locator('.chat-quote .component-references summary').click()
    await page.locator('.chat-quote').getByText('每件成品所用此部件成本参考：¥ 15.00', { exact: true }).waitFor()
    assert((await page.locator('.chat-quote .quote-confirmations').innerText()).includes('单件数量'))
    await page.locator('.el-message:visible').last().waitFor({ state: 'hidden' })
    for (const [name, width, height] of [['mobile', 390, 844], ['desktop', 1440, 1050]]) {
      await page.setViewportSize({ width, height })
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Unit quote overflow')
      await page.screenshot({ path: path.join(output, `unit-first-${name}.png`), animations: 'disabled' })
    }
    await page.getByRole('button', { name: '新对话', exact: true }).last().click()
    await page.getByRole('textbox', { name: '消息', exact: true }).fill('自动补全测试：按门牌需求补全报价，提供总体报价及审核清单')
    await page.getByText('授权本次对话资料及候选报价发送至 DeepSeek；补充需求将重新识别并更新报价', { exact: true }).click()
    await page.getByRole('button', { name: '发送消息', exact: true }).click()
    await page.locator('.chat-quote-total').getByText('¥ 141.60', { exact: true }).waitFor()
    await page.locator('.chat-run > details > summary').last().click()
    await page.locator('.chat-run').getByText('响应异常，自动恢复', { exact: true }).waitFor()
    assert.equal(await page.locator('.chat-run .chat-tool-step').count(), 4)
    assert.equal(await page.locator('.chat-run').getByText('自动补全并试算审核方案', { exact: true }).count(), 1)
    await page.locator('.chat-run > details > summary').last().click()
    await page.locator('.chat-quote .estimate-review').getByText('自动补全与费用审核清单', { exact: true }).waitFor()
    assert((await page.locator('.chat-quote .estimate-review').innerText()).includes('数量 · 暂定'))
    for (const [name, width, height] of [['desktop', 1440, 1050], ['mobile', 390, 844]]) {
      await page.setViewportSize({ width, height })
      await page.locator('.el-message:visible').last().waitFor({ state: 'hidden' })
      await page.locator('.chat-quote-total').scrollIntoViewIfNeeded()
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Estimate review overflow')
      await page.screenshot({ path: path.join(output, `estimate-review-${name}.png`), animations: 'disabled' })
    }
    await page.locator('.chat-quote .estimate-review').getByRole('button', { name: '修改并重新计价', exact: true }).click()
    const editDialog = page.getByRole('dialog', { name: '需求明细', exact: true })
    await editDialog.getByRole('textbox', { name: '暂定数量', exact: true }).fill('3')
    await editDialog.getByLabel('单件宽 (mm)', { exact: true }).fill('600')
    await editDialog.getByLabel('修改原因', { exact: true }).fill('审核调整暂定数量和尺寸')
    await editDialog.getByRole('button', { name: '保存并重新计价', exact: true }).click()
    await editDialog.waitFor({ state: 'hidden' })
    await page.locator('.chat-quote-total').getByText('¥ 234.80', { exact: true }).waitFor()
    await page.getByRole('button', { name: '查看与审核报价', exact: true }).click()
    await page.getByRole('button', { name: '批准报价', exact: true }).click()
    await page.getByRole('textbox', { name: '审核说明', exact: true }).fill('已核实补全参数和全部费用')
    await page.getByRole('textbox', { name: '正式报价条款', exact: true }).fill('按审核方案制作，不含税及安装，有效期7天')
    await page.getByText('已确认价格适用性、税费、运费、安装费及条款', { exact: true }).click()
    await page.getByRole('button', { name: '批准', exact: true }).click()
    await page.getByRole('dialog', { name: '批准报价', exact: true }).getByText('请逐项审核并明确确认Agent补全参数、估算费用和报价范围', { exact: true }).waitFor()
    await page.getByText('已逐项审核并确认补全参数、估算费用和报价范围', { exact: true }).click()
    await page.getByRole('button', { name: '批准', exact: true }).click()
    await page.getByRole('button', { name: '导出 CSV', exact: true }).waitFor()
    await page.locator('.el-drawer:visible .el-drawer__header button').click()
    await page.getByRole('dialog', { name: '明细与报价', exact: true }).waitFor({ state: 'hidden' })
    const resumeResponse = page.waitForResponse(response =>
      response.url().endsWith('/agent') && response.request().method() === 'POST')
    await page.getByRole('textbox', { name: '消息', exact: true }).fill('继续')
    await page.getByRole('button', { name: '发送消息', exact: true }).click()
    const response = await resumeResponse
    const request = response.request().postDataJSON()
    assert.equal(request.intent, 'resume')
    assert.equal(request.replace_existing, false)
    const resumed = await response.json()
    assert.equal(resumed.agent_runs[0].status, 'succeeded')
    assert.equal(resumed.agent_runs[0].usage.extraction_tokens, 0)
    assert.equal(resumed.agent_runs[0].usage.reused_line_count, 1)
    assert(!resumed.agent_runs[0].steps.some(step => step.tool.startsWith('extract_requirements')))
    assert.equal(resumed.requirements[0].width_mm, '600')
    assert.equal(resumed.requirements[0].estimate.assumptions[0].value, '3')
    await page.getByText('总体报价 · V3', { exact: false }).waitFor()
    await page.locator('.chat-quote-total').getByText('¥ 234.80', { exact: true }).waitFor()
    await page.locator('.el-message:visible').last().waitFor({ state: 'hidden' })
    await page.screenshot({ path: path.join(output, 'resume-without-extraction-mobile.png'), animations: 'disabled' })
    assert.deepEqual(errors, [])
    console.log('PASS: manual quote/approval/CSV, chat attachments, agent retry, follow-up conversation, text-only quote, history switching and mobile.')
    console.log('All data created in isolated UI test schema. No DeepSeek API requests made.')
  } catch (error) {
    await page.screenshot({ path: path.join(output, 'phase2-failure.png'), animations: 'disabled' })
    console.log('Visible dialogs:', await page.locator('.el-dialog:visible').allTextContents())
    throw error
  } finally { await browser.close() }
}
main().catch(e => { console.error(e); process.exitCode = 1 })
