"""initial_pricing_schema"""
from alembic import op
import sqlalchemy as sa


revision = '5137c9eef03b'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_logs_entity'), 'change_logs', ['entity'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name')
    )
    op.create_table('source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('sheet', sa.String(length=150), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('cells', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'sheet', 'row_number')
    )
    op.create_table('price_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=False),
    sa.Column('thickness_mm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('spec', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('process', sa.String(length=255), nullable=False),
    sa.Column('quality', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('price_kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('source_record_id', sa.Integer(), nullable=True),
    sa.Column('source_cell', sa.String(length=40), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_items_product_id'), 'price_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_price_items_status'), 'price_items', ['status'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_record_id', sa.Integer(), nullable=True),
    sa.Column('source_cell', sa.String(length=40), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rules_status'), 'pricing_rules', ['status'], unique=False)
    op.create_table('price_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_item_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['price_item_id'], ['price_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price_item_id', 'revision')
    )
    op.create_index(op.f('ix_price_revisions_price_item_id'), 'price_revisions', ['price_item_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_revisions_price_item_id'), table_name='price_revisions')
    op.drop_table('price_revisions')
    op.drop_index(op.f('ix_pricing_rules_status'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_price_items_status'), table_name='price_items')
    op.drop_index(op.f('ix_price_items_product_id'), table_name='price_items')
    op.drop_table('price_items')
    op.drop_table('source_records')
    op.drop_table('products')
    op.drop_table('source_documents')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_change_logs_entity'), table_name='change_logs')
    op.drop_table('change_logs')
    # ### end Alembic commands ###
