"""customer_requirements_and_quotes"""
from alembic import op
import sqlalchemy as sa


revision = '749fb8d9ee50'
down_revision = '5137c9eef03b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('customer', sa.String(length=150), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('extraction', sa.JSON(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_jobs_status'), 'requirement_jobs', ['status'], unique=False)
    op.create_table('customer_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['requirement_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_files_job_id'), 'customer_files', ['job_id'], unique=False)
    op.create_table('extraction_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('input_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['requirement_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_runs_job_id'), 'extraction_runs', ['job_id'], unique=False)
    op.create_table('quote_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('job_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.Column('approval_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['requirement_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'version')
    )
    op.create_index(op.f('ix_quote_drafts_job_id'), 'quote_drafts', ['job_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_drafts_job_id'), table_name='quote_drafts')
    op.drop_table('quote_drafts')
    op.drop_index(op.f('ix_extraction_runs_job_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index(op.f('ix_customer_files_job_id'), table_name='customer_files')
    op.drop_table('customer_files')
    op.drop_index(op.f('ix_requirement_jobs_status'), table_name='requirement_jobs')
    op.drop_table('requirement_jobs')
    # ### end Alembic commands ###
